// ============================================================
//  SEED PRODUCTS — Soum Deco
// ============================================================
//  29 products sourced from soumdeco.netlify.app (public
//  Cloudinary URLs from the reference site's Cloudinary account).
//  Used as offline fallback when NEXT_PUBLIC_SHEET_URL is not
//  configured or unreachable.
//
//  To replace with your own products:
//    1. Set up your own Google Sheet + Apps Script (see PROMPT.md)
//    2. Set NEXT_PUBLIC_SHEET_URL in .env
//    3. The API will automatically prefer the sheet over this seed.
// ============================================================

import type { SheetProduct } from "./sheet";

export const SEED_PRODUCTS: SheetProduct[] = [
  {
    id: "nouveau-5bzz3",
    name: "Service a table Blanc Luxe",
    description: "Service a table 24p \nModel: Blanc luxe \nMatière: Porcelaine \nProduit : Importation ",
    category: "arts de la table",
    price: 16600,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783035210/nouveau-5bzz3-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783035210/nouveau-5bzz3-1.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1783035210/nouveau-5bzz3-2.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1783035211/nouveau-5bzz3-3.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1783035211/nouveau-5bzz3-4.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1783035212/nouveau-5bzz3-5.jpg",
    featured: true,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 0,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-8a9wk",
    name: "Service a table Blanc luxe doré",
    description: "Service a table 24p \nModel: Blanc luxe doré \nMatière: Porcelaine \nProduit importation ",
    category: "arts de la table",
    price: 15000,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783035768/nouveau-8a9wk-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783035768/nouveau-8a9wk-1.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1783036606/nouveau-8a9wk-2.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1783036607/nouveau-8a9wk-3.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1783036607/nouveau-8a9wk-4.jpg",
    featured: false,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 1,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-ee3tk",
    name: "Service a table Blanc luxe avec reliefs",
    description: "Service a table 24p \nModel: Blanc Luxe avec reliefs \nMatière: porcelaine \nProduit importation ",
    category: "arts de la table",
    price: 15500,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783035898/nouveau-ee3tk-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783035898/nouveau-ee3tk-1.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1783036645/nouveau-ee3tk-2.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1783036646/nouveau-ee3tk-3.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1783036646/nouveau-ee3tk-4.jpg",
    featured: true,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 2,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-q7hs2",
    name: "Service a table Blanc cassé gris",
    description: "Service a table 24p \nModel: Blanc cassé gris \nMatière: Porcelaine \nProduit importation ",
    category: "arts de la table",
    price: 14500,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783036231/nouveau-q7hs2-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783036231/nouveau-q7hs2-1.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1783036671/nouveau-q7hs2-2.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1783036672/nouveau-q7hs2-3.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1783036672/nouveau-q7hs2-4.jpg",
    featured: false,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 3,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-c8e66",
    name: "Service a table beige luxe",
    description: "Service a table 24p \nModel: Beige luxe \nMatière: Céramique \nProduit importation ",
    category: "arts de la table",
    price: 16000,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783036302/nouveau-c8e66-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783036302/nouveau-c8e66-1.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1783036694/nouveau-c8e66-2.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1783036695/nouveau-c8e66-3.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1783036695/nouveau-c8e66-4.jpg",
    featured: false,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 4,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-7tdxy",
    name: "Service a café au lait A",
    description: "Service a café au lait 15P \nModel: A\nMatière: Porcelaine \nProduit importation ",
    category: "arts de la table",
    price: 10000,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783037715/nouveau-7tdxy-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783037715/nouveau-7tdxy-1.jpg",
    featured: false,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 5,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-ve70v",
    name: "Service a table avec motifs",
    description: "Service a table de 24 pièces \nMatière porcelaine \nProduit importation ",
    category: "arts de la table",
    price: 11400,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783130816/nouveau-ve70v-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783130816/nouveau-ve70v-1.jpg",
    featured: false,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 6,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-fudxe",
    name: "Service a table motif gris",
    description: "Service a table de 24 pièces \nMatière porcelaine \nProduit importation ",
    category: "arts de la table",
    price: 11400,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783131054/nouveau-fudxe-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783131054/nouveau-fudxe-1.jpg",
    featured: false,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 7,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-lbzkm",
    name: "Service a table Blue",
    description: "Service a table 24p \nModel: Blue\nMatière: Porcelaine \nProduit importation ",
    category: "arts de la table",
    price: 15000,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783589977/nouveau-lbzkm-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783589977/nouveau-lbzkm-1.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1783589978/nouveau-lbzkm-2.jpg",
    featured: false,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 8,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-qy4gc",
    name: "Service a table Blanc luxe doré ref02",
    description: "Service a table 24p \nModel: Blanc luxe doré \nMatière: Porcelaine \nProduit importation ",
    category: "arts de la table",
    price: 11400,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784566494/nouveau-qy4gc-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784566494/nouveau-qy4gc-1.jpg",
    featured: false,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 9,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-n9bpq",
    name: "Service a table 24p vert",
    description: "Apportez une touche d'élégance et de modernité à votre table avec ce magnifique service à table de 24 pièces en céramique de haute qualité. Son design raffiné, sa finition brillante et ses différentes couleurs s'intègrent parfaitement à tous les styles de décoration, du classique au contemporain.\nFabriqué en céramique résistante, ce service est conçu pour un usage quotidien tout en conservant son éclat et sa solidité au fil du temps. Grâce à sa finition soignée et à sa qualité supérieure, il est idéal aussi bien pour les repas en famille que pour recevoir vos invités.\nCaractéristiques :\n✔️ Service à table complet de 24 pièces\n✔️ Matière : Céramique premium\n✔️ Produit d'importation\n✔️ Disponible en différentes couleurs\n✔️ Finition brillante et élégante\n✔️ Très bonne résistance aux rayures et à l'usage quotidien\n✔️ Facile à nettoyer\n✔️ Convient à un usage quotidien et aux occasions spéciales\n✔️ Design moderne et intemporel\n✔️ Excellente qualité de fabrication\n✨ Disponible en stock.\n🚚 Livraison disponible dans toutes les wilayas.",
    category: "arts de la table",
    price: 16500,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784840229/nouveau-n9bpq-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784840229/nouveau-n9bpq-1.jpg",
    featured: false,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 10,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-wlcgv",
    name: "Coussin de voyage (Rose)",
    description: "Matière : silicone en fibre \nProduit local de très bonne qualité très souple ",
    category: "Coussins",
    price: 1200,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783103366/nouveau-wlcgv-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783103366/nouveau-wlcgv-1.jpg",
    featured: false,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 11,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-662bx",
    name: "Coussin de voyage (Marron)",
    description: "Matière : silicone en fibre \nProduit local de très bonne qualité très souple ",
    category: "Coussins",
    price: 1200,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783103424/nouveau-662bx-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783103424/nouveau-662bx-1.jpg",
    featured: true,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 12,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-jo3g2",
    name: "Mixeur plongeant Cristor HB- K55GN",
    description: "Vous rêvez d'une cuisine plus simple, rapide et efficace ? Ne cherchez plus ! Découvrez le compagnon idéal de toutes vos préparations culinaires : le Mixeur Plongeant 3-en-1 de Cristor. \n🥣✨\nQue ce soit pour de délicieux soupes, des smoothies vitaminés ou des pâtisseries réussies, il sait TOUT faire !\n\n💡 Pourquoi vous allez l'adorer ? (Ses caractéristiques)\nModèle performant : Référence HB-K55GN, conçu pour durer.\nMultifonction 3-en-1 : Un seul appareil pour trois actions indispensables :\n\nMélanger (pour vos veloutés, sauces et smoothies lisses).\n\nCouper / Hacher (grâce à son mini-hachoir inclus, parfait pour les oignons, herbes et viandes).\n\nFouetter (avec son fouet ballon pour des blancs en neige et des crèmes bien fermes).\n\nAccessoires inclus : Livré avec son verre doseur pratique pour mesurer et mixer directement dedans.\n\nDesign ergonomique : Une prise en main confortable et un look moderne gris/inox qui sublime votre cuisine.\n\nGarantie Sérénité : Profitez d'une garantie de 12 mois (1 an) pour cuisiner l'esprit tranquille ! 🛡️\n\n📦 Contenu de la boîte :\nLe bloc moteur du mixeur plongeant (Cristor)\nLe pied mixeur en inox\nLe bol hachoir avec ses lames performantes\nLe fouet adaptable\nLe verre doseur transparent\n\n📲 Commandez dès maintenant !\n📩 Prix et commande en DM (Message Privé) ou laissez un commentaire sous ce post !\n\n🚚 Livraison disponible (préciser vos conditions de livraison, ex: Livraison 58 wilayas disponible / Paiement à la livraison).\n\n#Cristor #MixeurPlongeant #CuisineFacile #RobotCuisine Electromenager Mixeur3en1 AstuceCuisine CuisineAlgérie EquipementMaison SmoothieTime Garantie1An RobotMultifonction",
    category: "Électroménager",
    price: 6000,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784652947/nouveau-jo3g2-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784652947/nouveau-jo3g2-1.jpg",
    featured: true,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 13,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-0brgt",
    name: "🍹 CRISTOR BLEND-IT : Noir",
    description: "Votre nouvel allié fraîcheur & cuisine ! 🌟\nVous rêvez de smoothies parfaits, de jus vitaminés ou d'épices fraîchement moulues en un clin d'œil ? Le mixeur Cristor Blend-it est fait pour vous !\n\nDisponible en deux coloris élégants (Noir chic 🖤 ou Blanc épuré 🤍) pour s'adapter parfaitement à votre cuisine.\n\nPourquoi vous allez l'adorer ?\n\n💪 Puissance optimale : 600W pour mixer sans effort tous vos ingrédients.\n\n🍹 Grande capacité : Un bol de 1.5 Litres, idéal pour toute la famille.\n\n⚙️ Multi-vitesses : 2 niveaux de vitesse pour un contrôle total de vos textures.\n\n🔪 Haute qualité : Lames en acier inoxydable ultra-résistantes.\n\n🔒 Sécurité garantie : Équipé d'un système de verrouillage de sécurité.\n\n☕ Le petit + : Livré avec son moulin à épices/café intégré !\n\n🛡️ Sérénité : Garantie de 12 mois (1 an).\n\n👉 Commandez le vôtre dès maintenant ! Les stocks sont limités.\n",
    category: "Électroménager",
    price: 6500,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784653111/nouveau-0brgt-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784653111/nouveau-0brgt-1.jpg",
    featured: true,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 14,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-emw96",
    name: "🍹 CRISTOR BLEND-IT : Blanc",
    description: "🍹 CRISTOR BLEND-IT : \nVotre nouvel allié fraîcheur & cuisine ! 🌟\nVous rêvez de smoothies parfaits, de jus vitaminés ou d'épices fraîchement moulues en un clin d'œil ? Le mixeur Cristor Blend-it est fait pour vous !\n\nDisponible en deux coloris élégants (Noir chic 🖤 ou Blanc épuré 🤍) pour s'adapter parfaitement à votre cuisine.\n\nPourquoi vous allez l'adorer ?\n\n💪 Puissance optimale : 600W pour mixer sans effort tous vos ingrédients.\n\n🍹 Grande capacité : Un bol de 1.5 Litres, idéal pour toute la famille.\n\n⚙️ Multi-vitesses : 2 niveaux de vitesse pour un contrôle total de vos textures.\n\n🔪 Haute qualité : Lames en acier inoxydable ultra-résistantes.\n\n🔒 Sécurité garantie : Équipé d'un système de verrouillage de sécurité.\n\n☕ Le petit + : Livré avec son moulin à épices/café intégré !\n\n🛡️ Sérénité : Garantie de 12 mois (1 an).\n\n👉 Commandez le vôtre dès maintenant ! Les stocks sont limités.\n",
    category: "Électroménager",
    price: 6500,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784653167/nouveau-emw96-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784653167/nouveau-emw96-1.jpg",
    featured: true,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 15,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-9h0mz",
    name: "Cocotte minute 06 litres Ref 01",
    description: "Cocotte-Minute NARDI – Qualité Italienne 🇮🇹\n\nDécouvrez la cocotte-minute NARDI, conçue en acier inoxydable de haute qualité pour une cuisson rapide, sûre et économique. Disponible en 6 L, 8 L, 10 L et 12 L, avec panier vapeur ou couscoussier selon le modèle. Compatible avec tous les types de feux, y compris l'induction, elle est dotée d'un système de sécurité renforcé et de poignées ergonomiques. \n\nUn choix idéal pour préparer facilement couscous, viandes, légumes, soupes et bien plus encore.\n\n✔️ Marque italienne\n✔️ Acier inoxydable de haute qualité\n✔️ 6L, 8L, 10L et 12L\n✔️ Avec panier vapeur ou couscoussier\n✔️ Compatible tous feux, y compris induction\n✔️ Garantie 12 mois",
    category: "Cuisine",
    price: 15000,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783965686/nouveau-9h0mz-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783965686/nouveau-9h0mz-1.jpg",
    featured: true,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 16,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-cxtbh",
    name: "Cocotte minute 06 Litres Ref 01",
    description: "Cocotte-Minute NARDI – Qualité Italienne 🇮🇹\n\nDécouvrez la cocotte-minute NARDI, conçue en acier inoxydable de haute qualité pour une cuisson rapide, sûre et économique. Disponible en 6 L, 8 L, 10 L et 12 L, avec panier vapeur ou couscoussier selon le modèle. Compatible avec tous les types de feux, y compris l'induction, elle est dotée d'un système de sécurité renforcé et de poignées ergonomiques.\n Un choix idéal pour préparer facilement couscous, viandes, légumes, soupes et bien plus encore.\n\n✔️ Marque italienne\n✔️ Acier inoxydable de haute qualité\n✔️ 6L, 8L, 10L et 12L\n✔️ Avec panier vapeur ou couscoussier\n✔️ Compatible tous feux, y compris induction\n✔️ Garantie 12 mois",
    category: "Cuisine",
    price: 15000,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784032383/nouveau-cxtbh-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784032383/nouveau-cxtbh-1.jpg",
    featured: true,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 17,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-a7qtb",
    name: "Cocotte minute 06 Litres Ref 03",
    description: "Cocotte-Minute NARDI – Qualité Italienne 🇮🇹\n\nDécouvrez la cocotte-minute NARDI, conçue en acier inoxydable de haute qualité pour une cuisson rapide, sûre et économique. Disponible en 6 L, 8 L, 10 L et 12 L, avec panier vapeur ou couscoussier selon le modèle. Compatible avec tous les types de feux, y compris l'induction, elle est dotée d'un système de sécurité renforcé et de poignées ergonomiques. \nUn choix idéal pour préparer facilement couscous, viandes, légumes, soupes et bien plus encore.\n\n✔️ Marque italienne\n✔️ Acier inoxydable de haute qualité\n✔️ 6L, 8L, 10L et 12L\n✔️ Avec panier vapeur ou couscoussier\n✔️ Compatible tous feux, y compris induction\n✔️ Garantie 12 mois",
    category: "Cuisine",
    price: 15000,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784033455/nouveau-a7qtb-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784033455/nouveau-a7qtb-1.jpg",
    featured: true,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 18,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-bxauf",
    name: "Cocotte minute 06 Litres Ref 04",
    description: "Cocotte-Minute NARDI – Qualité Italienne 🇮🇹\n\nDécouvrez la cocotte-minute NARDI, conçue en acier inoxydable de haute qualité pour une cuisson rapide, sûre et économique. Disponible en 6 L, 8 L, 10 L et 12 L, avec panier vapeur ou couscoussier selon le modèle. Compatible avec tous les types de feux, y compris l'induction, elle est dotée d'un système de sécurité renforcé et de poignées ergonomiques. \n\nUn choix idéal pour préparer facilement couscous, viandes, légumes, soupes et bien plus encore.\n\n✔️ Marque italienne\n✔️ Acier inoxydable de haute qualité\n✔️ 6L, 8L, 10L et 12L\n✔️ Avec panier vapeur ou couscoussier\n✔️ Compatible tous feux, y compris induction\n✔️ Garantie 12 mois",
    category: "Cuisine",
    price: 15000,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784034124/nouveau-bxauf-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784034124/nouveau-bxauf-1.jpg",
    featured: true,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 19,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-44rrv",
    name: "Miroir Noir",
    description: "MIROIR\nÉlégance et Simplicité\n\nCe miroir allie simplicité et élégance grâce à son cadre en résine de haute qualité avec une finition noire. Son design moderne et intemporel s'intègre parfaitement à tous les styles de décoration. Idéal pour agrandir visuellement votre espace tout en apportant une touche d'élégance à votre intérieur.\n\nDimensions :\n30 × 90 cm\nCadre : Résine, finition noire\nStyle : Moderne & intemporel\n\n\nUtilisation : Chambre, entrée, salon, dressing, couloir, bureau.\n",
    category: "Miroirs",
    price: 3750,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784811313/nouveau-44rrv-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784811313/nouveau-44rrv-1.jpg",
    featured: true,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 20,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-pmr6e",
    name: "Jarr Terracotta",
    description: "Jarre décorative en poterie – Terre cuite\n\nApportez une touche authentique et chaleureuse à votre intérieur avec cette magnifique jarre décorative en terre cuite. \n\nSon style artisanal, sa finition texturée effet vieilli et sa teinte terracotta en font une pièce de décoration idéale pour les salons, les entrées, les terrasses couvertes ou les espaces bohèmes et méditerranéens.\n\nElle est parfaite pour accueillir des fleurs séchées, des épis de blé, des pampas ou être exposée seule comme objet décoratif.\n\nCaractéristiques :\nMatière : Poterie en terre cuite\nHauteur : 50 cm\nCouleur : Terracotta effet vieilli\nStyle : Rustique, bohème, méditerranéen\nUtilisation : Décoration intérieure et extérieure abritée\nIdéale pour : Fleurs séchées, pampas, épis de blé ou décoration seule\nUne pièce élégante et intemporelle qui apportera du charme et du caractère à votre décoration.",
    category: "Décoration",
    price: 4250,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784803055/nouveau-pmr6e-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784803055/nouveau-pmr6e-1.jpg",
    featured: true,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 21,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-lzuvt",
    name: "Vase décoratif en poterie texturée – Blanc –",
    description: "\nApportez une touche de pureté et d'élégance à votre décoration intérieure avec ce magnifique vase décoratif en poterie. Sa couleur blanche intemporelle et sa finition texturée en relief en font une pièce raffinée qui s'intègre parfaitement dans tous les styles d'intérieur.\n\nHauteur : 50 cm (sans les fleurs ni les tiges décoratives)\nMatière : Poterie de haute qualité\nCouleur : Blanc\nFinition : Effet texturé en relief\nStyle : Moderne, minimaliste et contemporain\n\nUtilisation : Idéal pour accueillir des fleurs séchées, des branches décoratives ou comme objet de décoration à lui seul.\n\nEntretien : Se nettoie facilement avec un chiffon doux et sec.\n\nAvec son design sobre et élégant, ce vase est parfait pour embellir un salon, une chambre, une entrée ou un bureau. Associé à des fleurs séchées ou des tiges décoratives, il apporte une ambiance chic, chaleureuse et harmonieuse à votre intérieur.",
    category: "Décoration",
    price: 2500,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784835618/nouveau-lzuvt-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784835618/nouveau-lzuvt-1.jpg",
    featured: true,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 22,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-1scst",
    name: "Veilleuse cylindrique BB",
    description: "Veilleuse cylindrique en céramique Abat jour en tissu plessis lavable Model: 16c\nHauteur: 35cm ",
    category: "Lampe de chevet",
    price: 4500,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784483906/nouveau-1scst-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784483906/nouveau-1scst-1.jpg",
    featured: true,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 23,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-jpc5h",
    name: "Veilleuse OVNI",
    description: "Veilleuse décorative OVNI en céramique – Blanc neige – 50 cm\n\nApportez une touche de luminosité et d'élégance à votre intérieur avec cette magnifique veilleuse décorative en céramique. Son design en forme d'OVNI, sa finition blanc neige et ses accessoires dorés lui confèrent un style chic et intemporel, parfait pour sublimer tous les espaces de votre maison.\n\nCaractéristiques :\nHauteur totale : 50 cm\nMatière du pied : Céramique de haute qualité\nCouleur : Blanc neige\nDesign : Forme OVNI\nFinition : Accessoires métalliques dorés\nAbat-jour : Cylindrique\nMatière de l'abat-jour : Tissu plissé lavable\nOrigine : Produit d'importation\n\nAvec son design moderne et ses finitions soignées, cette veilleuse apporte une ambiance chaleureuse et raffinée à votre salon, votre chambre ou votre bureau. Élégante aussi bien allumée qu'éteinte, elle constitue un véritable objet de décoration qui s'harmonise parfaitement avec tous les styles d'intérieur.",
    category: "Lampe de chevet",
    price: 6200,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784826143/nouveau-jpc5h-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784826143/nouveau-jpc5h-1.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1784826143/nouveau-jpc5h-2.jpg",
    featured: true,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 24,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-vbva0",
    name: "Veilleuse BB8",
    description: "Veilleuse de table BB8 – Petit modèle\n\nApportez une touche d'élégance et de douceur à votre intérieur avec cette magnifique veilleuse BB8 petit modèle. Elle est dotée d'un pied en céramique composé de deux sphères à la finition brillante, sublimé par des détails dorés qui lui donnent un style chic et intemporel.\n\nSon abat-jour conique en tissu plissé, de couleur blanc cassé, diffuse une lumière douce et agréable. Le tissu est lavable, ce qui facilite son entretien tout en conservant son aspect élégant.\n\nCaractéristiques :\n- Modèle : BB8 – Petit modèle\n- Hauteur 45cm \n- Pied : Double céramique de haute qualité\n- Abat-jour : Conique en tissu plissé lavable\n- Couleur de l'abat-jour : Blanc cassé\n- Finition : Dorée\n- Style : Moderne, élégant et raffiné\n\nIdéale pour : Salon, chambre à coucher, table de chevet, bureau ou espace de décoration.\n\nCette veilleuse s'intègre parfaitement à tous les styles d'intérieur et apporte une ambiance chaleureuse et raffinée à votre maison.",
    category: "Lampe de chevet",
    price: 5800,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784826250/nouveau-vbva0-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784826250/nouveau-vbva0-1.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1784826251/nouveau-vbva0-2.jpg",
    featured: true,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 25,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-t6wy8",
    name: "Porte manteaux (Rose)",
    description: "Matière bois rouge de très bonne qualité \nDimensions 52*11cm \nCouleur : Blanc Rose ",
    category: "Meubes",
    price: 2200,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783103521/nouveau-t6wy8-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1783103521/nouveau-t6wy8-1.jpg",
    featured: false,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 26,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-c3bjf",
    name: "Meuble de salle de bain et cuisine en bois – Élégance & praticité",
    description: "\nApportez une touche chaleureuse et naturelle à votre salle de bain avec ce magnifique meuble de rangement au design moderne et épuré. Conçu pour allier esthétique et fonctionnalité, il offre une grande capacité de rangement tout en sublimant votre espace.\n\nCaractéristiques :\n\n📏 Dimensions : 110 × 110 cm (hauteur × largeur)\n\n🌳 Structure et portes : Bois de hêtre robuste et résistant\n\n🪵 Étagères : MDF de très haute qualité, solide et durable\n\n🚪 2 portes pour un rangement discret et organisé\n\n🧺 2 paniers de rangement en tissu inclus\n\n📚 Étagères ouvertes pour un rangement pratique\n\n🎨 Style : Scandinave, moderne et naturel\n\n🏡 Idéal pour : Salle de bain, buanderie ou espace de rangement.\n\n🚚 Livraison disponible dans les 58 wilayas.\n\n✨ SOUM DÉCO – L'élégance au cœur de votre maison.",
    category: "Meubes",
    price: 17250,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784832581/nouveau-c3bjf-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784832581/nouveau-c3bjf-1.jpg~~~https://res.cloudinary.com/anhvhy4j/image/upload/v1784832581/nouveau-c3bjf-2.jpg",
    featured: true,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 27,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
  {
    id: "nouveau-nbcsa",
    name: "Meuble de rangements Ref01",
    description: "Meuble de rangements de trois étages \nMatière : Mdf \nHauteur : 1m03cm \nLargeur: 35cm \nProfondeur: 35 \nPoids: 22 kilos \nÉtagères: 31*30*30cm ",
    category: "Meubes",
    price: 15500,
    image: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784832741/nouveau-nbcsa-1.jpg",
    images: "https://res.cloudinary.com/anhvhy4j/image/upload/v1784832741/nouveau-nbcsa-1.jpg",
    featured: true,
    isSpecialOffer: false,
    variations: "",
    variants: "",
    stock: null,
    highlights: "",
    sortOrder: 28,
    badge: "",
    oldPrice: null,
    quantityTiers: "",
  },
];
